IRODSFS_EXECUTABLE: irodsFs_v32.rhel5.x86_64
IRODSFS_DESTINATION: /usr/local/bin/irodsFs.x86_64
IRODSFS_LINK: /usr/local/bin/irodsFs

ICOMMANDS_TAR: icommands_v331.centos.x86_64.tar.bz2
ICOMMANDS_DESTINATION: /opt
BIN_PATH: /usr/local/bin

ICOMMANDS_URL: https://files.renci.org/pub/irods/releases/4.1.11/centos7/irods-icommands-4.1.11-centos7-x86_64.rpm
