IRODSFS_EXECUTABLE: irodsFs_v32.ubuntu12.x86_64
IRODSFS_DESTINATION: /usr/local/bin/irodsFs.x86_64
IRODSFS_LINK: /usr/local/bin/irodsFs

ICOMMANDS_TAR: icommands_v331.ubuntu.x86_64.tar.bz2
ICOMMANDS_DESTINATION: /opt
BIN_PATH: /usr/local/bin

ICOMMANDS_URL: https://files.renci.org/pub/irods/releases/4.1.9/ubuntu14/irods-icommands-4.1.9-ubuntu14-x86_64.deb
