---

xsession_path: /usr/bin/X
xterm_path: /usr/bin/xinit

dependencies:
  - qt5-qmake
  - qtbase5-dev
  - libqt5svg5-dev
  - libcurl4-nss-dev
  - qt5-default
  - g++

irods_files:
  - { url: 'ftp://ftp.renci.org/pub/irods/releases/4.1.9/ubuntu14/irods-runtime-4.1.9-ubuntu14-x86_64.deb', dest: '/tmp/irods-runtime.deb', checksum: '0c44062d184150469bf0662ee7aca888796067bc' }
  - { url: 'ftp://ftp.renci.org/pub/irods/releases/4.1.9/ubuntu14/irods-icommands-4.1.9-ubuntu14-x86_64.deb', dest: '/tmp/irods-icommands.deb', checksum: '5e10ccc925c7c9de8a48d9e5575e67a2751de7d7' }
  - { url: 'ftp://ftp.renci.org/pub/irods/releases/4.1.9/ubuntu14/irods-dev-4.1.9-ubuntu14-x86_64.deb', dest: '/tmp/irods-dev.deb', checksum: '6a46e71bc08c31bfb89ce98ec97b80f874e2a13e' }
