---

# If MOUNT_SOURCE is already mounted somewhere else (e.g. /home for a legacy instance or /vol1 for a volume), don't change it
- set_fact:
    disk_mounted_elsewhere: true
  when: '(item.device == "/dev/{{ MOUNT_SOURCE }}") and (item.mount != "/mnt")'
  with_items: '{{ ansible_mounts }}'

- name: 'Ephemeral disk unmounted from default location'
  mount:
    path: '/mnt'
    state: 'unmounted'
  when: 'disk_mounted_elsewhere == false'

- name: 'Ephemeral disk removed from /etc/fstab'
  mount:
    path: '/mnt'
    state: 'absent'
  when: 'disk_mounted_elsewhere == false'

- name: 'Ephemeral disk mounted'
  mount:
    path: '{{ MOUNT_PATH }}'
    src: '/dev/{{ MOUNT_SOURCE }}'
    fstype: '{{ MOUNT_TYPE }}'
    state: 'mounted'
  when: '(ansible_devices.{{ MOUNT_SOURCE }} is defined) and (disk_mounted_elsewhere == false)'

- name: 'Data loss warning for Ephemeral storage'
  copy:
    src: 'DATA-LOSS-WARNING.txt'
    dest: '{{ MOUNT_PATH }}/DATA-LOSS-WARNING.txt'
  when: '(ansible_devices.{{ MOUNT_SOURCE }} is defined) and (disk_mounted_elsewhere == false)'
