---

# If /dev/vdb is already mounted somewhere else (e.g. /home for a legacy instance), don't change it
- set_fact:
    vdb_mounted: true
  when: 'item.device == "/dev/vdb" and item.mount != "/mnt"'
  with_items: '{{ ansible_mounts }}'

- name: 'Ephemeral disk mounted'
  mount:
    path: '{{ MOUNT_PATH }}'
    src: '/dev/{{ MOUNT_SOURCE }}'
    fstype: '{{ MOUNT_TYPE }}'
    state: 'mounted'
  when: '(ansible_devices.{{ MOUNT_SOURCE }} is defined) and (vdb_mounted is not defined)'

- name: 'Data loss warning for Ephemeral storage'
  copy:
    src: 'DATA-LOSS-WARNING.txt'
    dest: '{{ MOUNT_PATH }}/DATA-LOSS-WARNING.txt'
  when: '(ansible_devices.{{ MOUNT_SOURCE }} is defined) and (vdb_mounted is not defined)'
