---
- name: Copy desktop background to instance
  copy:
    src: "{{ background_img }}"
    dest: '{{ background_dest }}'

- name: check if XFCE is desktop environment
  stat:
    path: '/usr/bin/xfce4-session'
  register: xfce

- name: desktop environment is XFCE
  set_fact:
    change_background_cmd: 'xfconf-query -c xfce4-desktop --property /backdrop/screen0/monitor0/workspace0/last-image --create --type string --set'
  when: xfce.stat.exists

- name: check if Gnome is desktop environment
  stat:
    path: '/usr/bin/gnome-session'
  register: gnome

- name: desktop environment is Gnome
  set_fact:
    change_background_cmd: 'gconftool-2 -s -t string /desktop/gnome/background/picture_filename'
  when: gnome.stat.exists and not xfce.stat.exists

# gsettings requires that a dbus-daemon is running. dbus-launch is used to launch it
# because it exits and returns environment variables. $() sources these variables so
# we can kill the PID and avoid having a bunch of rogue dbus-daemons.
- name: Change desktop background
  become: yes
  become_user: '{{ ATMOUSERNAME }}'
  shell: 'export $(dbus-launch); {{ change_background_cmd }} "{{ background_dest }}" && kill $DBUS_SESSION_BUS_PID'
