---

- name: check if XFCE is desktop environment
  stat:
    path: '/usr/bin/xfce4-session'
  register: xfce_result

- name: desktop environment is XFCE
  set_fact:
    terminal_application: 'xfce4-terminal'
  when: xfce_result.stat.exists

- name: check if Gnome is desktop environment
  stat:
    path: '/usr/bin/gnome-session'
  register: gnome_result

- name: desktop environment is Gnome
  set_fact:
    terminal_application: 'gnome-terminal'
  when: gnome_result.stat.exists

- name: install terminal
  package:
    name: '{{ terminal_application }}'
    state: latest
